apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendly-api
  namespace: calendly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendly-api
  template:
    metadata:
      labels:
        app: calendly-api
    spec:
      containers:
        - name: api
          image: calendlyacr25007.azurecr.io/calendly-api:v1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
          envFrom:
            - secretRef:
                name: calendly-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: calendly-api
  namespace: calendly
spec:
  type: LoadBalancer
  selector:
    app: calendly-api
  ports:
    - port: 80
      targetPort: 3000
